In [1]:
import torch
import numpy as np

In [3]:
li = torch.zeros(3,2,3)
li_ = np.zeros((3,3,3))
li_ = (torch.from_numpy(li_)+4).pow(2)

In [12]:
li.transpose(1,2).shape

torch.Size([3, 3, 2])

In [18]:
li = li.squeeze(0).shape

torch.Size([2, 3])

In [20]:
li.unsqueeze(2).shape

torch.Size([1, 2, 1, 3])

In [25]:
torch.cat([li,li_],1).shape

torch.Size([3, 5, 3])

In [4]:
li.to('cuda')

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]], device='cuda:0')

In [9]:
x = torch.tensor([[1.,0.],[-1.,2.]],requires_grad=True)
z = x.pow(3).sum()
z.backward()
x.grad

tensor([[ 3.,  0.],
        [ 3., 12.]])

## Dataset

In [6]:
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor
training_data = datasets.FashionMNIST(root='data',train=True,transform=ToTensor())
batch = 10
training_loader = DataLoader(training_data,batch_size=batch,shuffle=True)


In [7]:
for x,y in training_loader:
    print(x,y)
    break

tensor([[[[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0039, 0.0000, 0.0000],
          ...,
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]]],


        [[[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          ...,
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]]],


        [[[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..